### ISSUE TITLE
Aprendendo o que é Ruby

### ISSUE THREAD

**Issue by cassiosantana** [cassiosantana/my-study-plan#149]
- [x] [Introdução ao curso](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/43)
- [x] [O que são Ruby, Rails e Gems?](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/42)
- [x] [O ambiente de desenvolvimento](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/41)
- [x] [Brincando no shell do Ruby](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/40)
- [x] [Executando um código fonte](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/39)
- [x] [Strings](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/38)
- [x] [Operações com Strings](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/37)
- [x] [Números](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/36)
- [x] [Símbolos](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/35)
- [x] [Arrays](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/34)
- [x] [Hashes](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/33)
- [x] [Input de dados](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/32)
- [x] [Condicionais](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/31)
- [x] [Laços](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/30)
- [x] [Métodos](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/29)
- [x] [Verificar se a palavra é palíndromo](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/27)
- [x] [Solução prática](https://github.com/cassiosantana/aprendendo-o-que-e-ruby/issues/28)
