### ISSUE TITLE
Ruby, Introdução a orientação a objetos

### ISSUE THREAD

**Issue by cassiosantana** [cassiosantana/my-study-plan#150]
- [x] [O que são classes e objetos](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/10)
- [x] [O que é herança](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/13)
- [x] [Visibilidade de métodos](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/15)
- [x] [Métodos e variáveis](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/11)
- [x] [Métodos e variáveis de Classe](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/14)
- [x] [Conta bancária](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/16)
- [x] [Importando outro arquivo](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/12)
- [x] [Introdução ao Rails](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/17)
- [x] [Banco de dados com Rails](https://github.com/cassiosantana/ruby-introducao-orientacao-objetos/issues/18)
