### ISSUE TITLE
Ruby on Rails, Introdução ao MVC

### ISSUE THREAD

**Issue by cassiosantana** [cassiosantana/my-study-plan#151]
- [x] [Apresentação inicial, objetivos e requisitos básicos](https://github.com/cassiosantana/ror-introducao-mvc/issues/9)
- [x] [Conceitos do MVC](https://github.com/cassiosantana/ror-introducao-mvc/issues/12)
- [x] [Criando um CRUD](https://github.com/cassiosantana/ror-introducao-mvc/issues/10)
- [x] [Praticando o MVC - O que são rotas](https://github.com/cassiosantana/ror-introducao-mvc/issues/11)
- [x] [Criando novas rotas](https://github.com/cassiosantana/ror-introducao-mvc/issues/13)
- [x] [Dúvidas e comentários finais](https://github.com/cassiosantana/ror-introducao-mvc/issues/14)
- [x] [Certify your knowledge](https://github.com/cassiosantana/ror-introducao-mvc/issues/15)
